# Generated by Django 4.0.4 on 2022-04-27 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'ягода',
                'verbose_name_plural': 'ягоды',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=200, verbose_name='текст слов на торте')),
                ('berries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.berries', verbose_name='ягода')),
            ],
            options={
                'verbose_name': 'декор',
                'verbose_name_plural': 'декоры',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'декор',
                'verbose_name_plural': 'декоры',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('deliver_at', models.DateTimeField(blank=True, null=True, verbose_name='когда доставить')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставки',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.CharField(max_length=200, verbose_name='фигура')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'количество уровней',
                'verbose_name_plural': 'количество уровней',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'топпинг',
                'verbose_name_plural': 'топпинги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('cake', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cake.cake', verbose_name='торт')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cake.client', verbose_name='клиент')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cake.delivery', verbose_name='доставка')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.decor', verbose_name='декор'),
        ),
        migrations.AddField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.form', verbose_name='форма'),
        ),
        migrations.AddField(
            model_name='cake',
            name='levels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.levels', verbose_name='количество слоев'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.topping', verbose_name='топпинг'),
        ),
    ]
