# Generated by Django 4.0.4 on 2022-04-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'торт', 'verbose_name_plural': 'торты'},
        ),
    ]
