# Generated by Django 4.0.4 on 2022-04-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.berries', verbose_name='ягода'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cake', to='cake.decor', verbose_name='декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='words',
            field=models.CharField(blank=True, max_length=200, verbose_name='текст слов на торте'),
        ),
    ]
