# Generated by Django 4.0.4 on 2022-05-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_cake_berries_alter_cake_decor_alter_cake_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
    ]
